name: CI/CD
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Run a one-line script
      run: "echo Hello, world!"

  deploy-stage:
    runs-on: ubuntu-latest
    environment: staging
    needs: [build]
    steps:
    - name: Deploy
      run: echo "Deploying staging"      
